warning_threshold: 15

nesting:
  type_level: 3

identifier_name:
  excluded:
    - id
    - ok
    - up
    - to

line_length:
  warning: 150

function_parameter_count:
  warning: 10
  error: 15

file_length:
  warning: 500

type_body_length:
  warning: 400
  error: 450

excluded:
  - RichEditorView
  - TelegraphUITests

